language: node_js

node_js:
  - "0.12"

sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgmp3-dev
  - sudo apt-get install libdb-dev
  - build/install-gnu-cobol.sh
  - build/install-mono.sh
  - build/install-antlr.sh
